# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hive < Formula
  desc "Manage multiple AI agent sessions in tmux"
  homepage "https://github.com/fjcasti1/hive"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fjcasti1/hive/releases/download/v0.1.1/hive_darwin_amd64.tar.gz"
      sha256 "295dddf5edb61b475c73a05f1a377c19dabaec83c699afa10c72f5b6395912ec"

      define_method(:install) do
        bin.install "hive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fjcasti1/hive/releases/download/v0.1.1/hive_darwin_arm64.tar.gz"
      sha256 "0e5e7dc1b91177569a1b04c85568ad2da804448e83771f61bd5ddf8d8e9b4608"

      define_method(:install) do
        bin.install "hive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjcasti1/hive/releases/download/v0.1.1/hive_linux_amd64.tar.gz"
      sha256 "20e4bad8098a3664d43d0220da406f6ee8dffa4fcad535942e038540d4e619d9"
      define_method(:install) do
        bin.install "hive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjcasti1/hive/releases/download/v0.1.1/hive_linux_arm64.tar.gz"
      sha256 "87e4997178c5bb5be9021bedefe401f56149bf1fcef915821c35c32a5a5261e1"
      define_method(:install) do
        bin.install "hive"
      end
    end
  end

  test do
    system "#{bin}/hive", "--version"
  end
end
