# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hive < Formula
  desc "Manage multiple AI agent sessions in tmux"
  homepage "https://github.com/fjcasti1/hive"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fjcasti1/hive/releases/download/v1.4.0/hive_darwin_amd64.tar.gz"
      sha256 "b64da95ec406b74df4d9da5d568e9f1a2754043d04441313548386500c7e8822"

      define_method(:install) do
        bin.install "hive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fjcasti1/hive/releases/download/v1.4.0/hive_darwin_arm64.tar.gz"
      sha256 "13a1c7a50da6e3e073efe158832be05a6481ea7fd2fdf75b15deeca9311e4e8f"

      define_method(:install) do
        bin.install "hive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjcasti1/hive/releases/download/v1.4.0/hive_linux_amd64.tar.gz"
      sha256 "6f1a8f8324859e41a6527861795ad6555e30f6c94fb65a6399f3c2d5c7946287"
      define_method(:install) do
        bin.install "hive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjcasti1/hive/releases/download/v1.4.0/hive_linux_arm64.tar.gz"
      sha256 "7293b052239975dd29045eb42f88098f9e4618650b6f1d63ae1c4003d962d9e3"
      define_method(:install) do
        bin.install "hive"
      end
    end
  end

  test do
    system "#{bin}/hive", "--version"
  end
end
